name: Deploy URL lambda 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Deploy code to Lambda
      uses: kalagarapraveen/UrlShorten_aws_cdk@v1.0.1
      with:
        lambda_layer_arn: 'arn:aws:lambda:ap-south-1:028642144348:function:URLstack-urlshorternstg06C452BC-8WZW7B9Yj0hb'
        lambda_function_name: 'main'
        lambda_region: ${{ secrets.REGION }}
        requirements_txt: 'requirements.txt'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}