name: Deploy URL lambda 

on:
  push:
    branches:
      - main

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Deploy code to Lambda
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key': ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
      
    - name: install npm
      run: 'sudo apt update -y && sudo apt install nodejs npm -y'

    - name: install aws_cdk
      run: 'sudo npm install -g aws-cdk'

    - name: install requirements
      run: 'pip3 install -r requirements.txt'
      working-directory: CDK-AWS

    - name: CDK Synth
      run: cdk synth
      working-directory: CDK-AWS

    - name: CDK Deploy Url stac
      run: cdk deploy URLstack
      working-directory: CDK-AWS

      